package main

import (
	"html/template"
	"os"
)

func writeHTMLReport(r *Result, filename string) error {
	const page = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>WebScan Report</title>

<style>
body {
	font-family: system-ui, sans-serif;
	max-width: 1000px;
	margin: 40px auto;
	padding: 0 20px;
	background: #f5f5f5;
	color: #222;
}

.card {
	background: white;
	border-radius: 12px;
	padding: 20px;
	margin-bottom: 20px;
	box-shadow: 0 2px 8px rgba(0,0,0,.08);
}

h1 {
	margin-top: 0;
}

table {
	width: 100%;
	border-collapse: collapse;
}

td, th {
	padding: 10px;
	border-bottom: 1px solid #ddd;
	text-align: left;
}

.ok {
	color: green;
}

.missing {
	color: #b00;
}

small {
	color: #666;
}
</style>
</head>

<body>

<div class="card">
<h1>WebScan Report</h1>
<p><small>Generated by WebScan</small></p>
</div>

<div class="card">
<h2>Summary</h2>

<table>
<tr><th>HTTP Status</th><td>{{.Summary.StatusCode}}</td></tr>
<tr><th>HTTPS</th><td>{{if .Summary.HTTPS}}YES{{else}}NO{{end}}</td></tr>
<tr><th>TLS</th><td>{{if .Summary.TLSVersion}}{{.Summary.TLSVersion}}{{else}}-{{end}}</td></tr>
<tr><th>Security Headers</th><td>{{.Summary.SecurityHeaders}}</td></tr>
<tr><th>Redirects</th><td>{{.Summary.RedirectCount}}</td></tr>
<tr><th>DNS Records</th><td>{{.Summary.DNSCount}}</td></tr>
<tr><th>robots.txt</th><td>{{.Summary.Robots}}</td></tr>
<tr><th>sitemap.xml</th><td>{{.Summary.Sitemap}}</td></tr>
</table>
</div>

<div class="card">
<h2>Security Score</h2>

<table>
<tr><th>Score</th><td>{{.Score.Score}} / 100</td></tr>
<tr><th>HTTPS</th><td>{{.Score.HTTPS}}</td></tr>
<tr><th>TLS</th><td>{{.Score.TLS}}</td></tr>
<tr><th>Headers</th><td>{{.Score.Headers}} / {{.Score.TotalHeaders}}</td></tr>
<tr><th>robots.txt</th><td>{{.Score.Robots}}</td></tr>
<tr><th>sitemap.xml</th><td>{{.Score.Sitemap}}</td></tr>
</table>

</div>

<div class="card">
<h2>Target</h2>

<table>
<tr><th>Target</th><td>{{.Target}}</td></tr>
<tr><th>Scan Profile</th><td>{{.Profile}}</td></tr>
<tr><th>Final URL</th><td>{{.FinalURL}}</td></tr>
<tr><th>Status</th><td>{{.StatusText}}</td></tr>
<tr><th>Server</th><td>{{.Server}}</td></tr>
<tr><th>Content-Type</th><td>{{.ContentType}}</td></tr>
<tr><th>Response Time</th><td>{{.ResponseTime}}</td></tr>
<tr><th>Scan Time</th><td>{{.ScanTime}}</td></tr>
<tr><th>Scan Duration</th><td>{{.ScanDuration}}</td></tr>
<tr><th>HTTPS</th><td>{{.HTTPS}}</td></tr>
<tr><th>TLS</th><td>{{.TLSVersion}}</td></tr>
<tr><th>TLS Subject</th><td>{{if .TLSInfo}}{{.TLSInfo.Subject}}{{else}}-{{end}}</td></tr>
<tr><th>TLS Issuer</th><td>{{if .TLSInfo}}{{.TLSInfo.Issuer}}{{else}}-{{end}}</td></tr>
<tr><th>TLS Expires</th><td>{{if .TLSInfo}}{{.TLSInfo.Expires}}{{else}}-{{end}}</td></tr>
<tr><th>Days Left</th><td>{{if .TLSInfo}}{{.TLSInfo.DaysLeft}}{{else}}-{{end}}</td></tr>
</table>
</div>

<div class="card">
<h2>DNS</h2>

<ul>
{{range .DNS}}
<li>{{.}}</li>
{{else}}
<li>No address found</li>
{{end}}
</ul>

</div>

<div class="card">
<h2>Security Headers</h2>

<table>
<tr>
<th>Header</th>
<th>Value</th>
</tr>

{{range $key, $value := .Headers}}
<tr>
<td>{{$key}}</td>
<td class="{{if eq $value "MISSING"}}missing{{else}}ok{{end}}">
{{$value}}
</td>
</tr>
{{end}}

</table>
</div>

<div class="card">
<h2>Redirect Chain</h2>

<ol>
{{range .Redirects}}
<li>{{.}}</li>
{{else}}
<li>No redirects detected</li>
{{end}}
</ol>

</div>

<div class="card">
<h2>Standard Resources</h2>

<table>
<tr>
<th>Resource</th>
<th>Status</th>
</tr>

<tr>
<td>robots.txt</td>
<td>{{.Robots}}</td>
</tr>

<tr>
<td>sitemap.xml</td>
<td>{{.Sitemap}}</td>
</tr>

</table>
</div>

</body>
</html>`

	tmpl, err := template.New("report").Parse(page)
	if err != nil {
		return err
	}

	file, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer file.Close()

	return tmpl.Execute(file, r)
}
